#src/Osel/MusicsheetBundle/Resources/config/routing.yml

osel_musicsheet_get_composers:
    path:     /getComposers/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:getComposers, id: 0 }
    options:
        expose: true

osel_musicsheet_get_composers_user:
    path:     /getComposersUser/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:getComposersUser, id: 0 }
    options:
        expose: true

osel_musicsheet_get_musicsheets:
    path:     /getMusicsheets/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:getMusicsheets, id: 0 }
    options:
        expose: true

osel_musicsheet_get_musicsheets_user:
    path:     /getMusicsheetsUser/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:getMusicsheetsUser, id: 0 }
    options:
        expose: true

osel_musicsheet_get_parts:
    path:     /getParts/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:getParts, id: 0 }

osel_musicsheet_get_parts_user:
    path:     /getPartsUser/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:getPartsUser, id: 0 }

osel_musicsheet_download_part:
    path:     /download/part/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:downloadPart, id: 0 }

osel_musicsheet_test_change_url:
    path:     /test/changeUrl
    defaults: { _controller: OSELMusicsheetBundle:Test:changeURL}

osel_musicsheet_index:
    path:     /
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:index}

osel_musicsheet_gestion:
    path:     /Gestion/{idComposer}/{idMusicsheet}/{idPart}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:gestion, idComposer: 0, idMusicsheet: 0, idPart: 0 }

osel_musicsheet_view:
    path:     /{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:view, id: 0 }

osel_musicsheet_view_part:
    path:     /part/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:viewPart, id: 0 }

osel_musicsheet_modify:
    path:     /modify/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:modify, id: 0 }
    options:
        expose: true

osel_musicsheet_modify_complete:
    path:     /modifycomplete/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:modifyComplete, id: 0 }
    options:
        expose: true