osel_event_add_place:
    path:     /nouvel-endroit-de-weekend
    defaults: { _controller: OSELEventBundle:Places:addPlace }

osel_event_modify_place:
    path:     /modifier-endroit-de-weekend/{id}
    defaults: { _controller: OSELEventBundle:Places:modifyPlace, id: 0 }

osel_event_delete_place:
    path:     /supprimer-endroit-de-weekend/{id}
    defaults: { _controller: OSELEventBundle:Places:deletePlace, id: 0 }

osel_event_list_places:
    path:     /endroits-de-weekend/{page}/{criteria}/{desc}/{active}/{nbPerPage}
    defaults: { _controller: OSELEventBundle:Places:indexPlaces, page: 1, criteria: lastname, desc: 0, active: 0, nbPerPage: 20 }

osel_event_view_place:
    path:     /endroit-de-weekend/{id}
    defaults: { _controller: OSELEventBundle:Places:viewPlace, id: 0 }

osel_event_add:
    path:     /nouveau-weekend
    defaults: { _controller: OSELEventBundle:Events:add }

osel_event_modify:
    path:     /modifier-weekend/{id}
    defaults: { _controller: OSELEventBundle:Events:modify, id: 0 }

osel_event_delete:
    path:     /supprimer-weekend/{id}
    defaults: { _controller: OSELEventBundle:Events:delete, id: 0 }

osel_event_list:
    path:     /liste-des-weekends/{page}/{criteria}/{desc}/{active}/{nbPerPage}
    defaults: { _controller: OSELEventBundle:Events:index, page: 1, criteria: lastname, desc: 0, active: 0, nbPerPage: 20 }

osel_event_view:
    path:     /weekend/{id}
    defaults: { _controller: OSELEventBundle:Events:view, id: 0 }

osel_event_activate:
    path:   /activate-event/{id}
    defaults:  { _controller: OSELEventBundle:Events:activateEvent, id: 0}

osel_event_add_inscription:
    path:     /nouvelle-inscription-weekend
    defaults: { _controller: OSELEventBundle:Inscriptions:add }

osel_event_add_individual_inscription:
    path:     /nouvelle-inscription-weekend-individuelle/{id}
    defaults: { _controller: OSELEventBundle:Inscriptions:addIndividual, id: 0 }

osel_event_modify_inscription:
    path:     /modifier-inscription-weekend/{id}/{idEvent}
    defaults: { _controller: OSELEventBundle:Inscriptions:modify, id: 0 , idEvent: 0}

osel_event_delete_inscription:
    path:     /supprimer-inscription-weekend/{id}
    defaults: { _controller: OSELEventBundle:Inscriptions:delete, id: 0 }

osel_event_list_inscription:
    path:     /liste-des-inscriptions-weekends/{id}/{page}/{criteria}/{desc}/{presence}/{nbPerPage}
    defaults: { _controller: OSELEventBundle:Inscriptions:index, page: 1, criteria: lastname, desc: 0, presence: 1, nbPerPage: 50 }
    
osel_event_list_inscription_simple:
    path:     /liste-des-inscriptions-weekends-simple/{id}/{page}/{criteria}/{desc}/{presence}/{nbPerPage}
    defaults: { _controller: OSELEventBundle:Inscriptions:indexSimple, page: 1, criteria: lastname, desc: 0, presence: 1, nbPerPage: 50 }

osel_event_list_non_inscrits:
    path:     /liste-des-non-inscrits/{id}/{page}/{criteria}/{desc}/{nbPerPage}
    defaults: { _controller: OSELEventBundle:Inscriptions:noninscrits, page: 1, criteria: lastname, desc: 0, nbPerPage: 50 }

osel_event_view_inscription:
    path:     /inscription/{id}
    defaults: { _controller: OSELEventBundle:Inscriptions:view, id: 0 }

osel_event_inscription_complete:
    path:   /payement-complete/{id}/{idEvent}
    defaults:  { _controller: OSELEventBundle:Inscriptions:modifyComplete, id: 0 , idEvent: 0}

osel_event_inscription_prix:
    path:   /inscription-prix/{id}
    defaults:  { _controller: OSELEventBundle:Inscriptions:modifyPrix, id: 0 }
    options:
                expose: true

osel_event_test_subscriptions:
    path:   /test/nbsubscriptions
    defaults:  { _controller: OSELEventBundle:Test:nbsubscriptions}

osel_event_export:
    path:   /export-event/{id}
    defaults:  { _controller: OSELEventBundle:Inscriptions:exportEvent, id: 0}