<?php

namespace OSEL\DocBundle\Repository;

/**
 * YearDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
