score:
    resource: "@ScoreBundle/Resources/config/routing.yml"
    prefix:   /partitions

osel_news:
    resource: "@OSELNewsBundle/Resources/config/routing.yml"
    prefix:   /news

osel_media:
    resource: "@OSELMediaBundle/Resources/config/routing.yml"
    prefix:   /media

osel_event:
    resource: "@OSELEventBundle/Resources/config/routing.yml"
    prefix:   /event

osel_info:
    resource: "@OSELInfoBundle/Resources/config/routing.yml"
    prefix:   /info

osel_core:
    resource: "@OSELCoreBundle/Resources/config/routing.yml"
    prefix:   /

osel_user:
    resource: "@OSELUserBundle/Resources/config/routing.yml"
    prefix:   /membres

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

login:
    path:   /login
    defaults:  { _controller: OSELUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

register:
    path:   /register
    defaults:  { _controller: OSELUserBundle:Security:register }
    
delete:
    path:   /delete/{id}
    defaults:  { _controller: OSELUserBundle:Security:delete, id: 0 }

modify:
    path:   /modify/{id}
    defaults:  { _controller: OSELUserBundle:Security:modify, id: 0 }

changePass:
    path:   /changepass/{id}
    defaults:  { _controller: OSELUserBundle:Security:changePass, id: 0 }

user_modify_complete:
    path:   /modifyComplete/{id}
    defaults:  { _controller: OSELUserBundle:Security:modifyComplete, id: 0 }

set_passwd:
    path: /setPass/{set}/{id}/{sha}
    defaults: {_controller: OSELUserBundle:Security:setPass, set: 1 }

reset_passwd:
    path: /resetPass/{set}/{id}/{sha}
    defaults: {_controller: OSELUserBundle:Security:setPass, set: 0 }

send_reset_mail:
    path: /resetMail
    defaults: {_controller: OSELUserBundle:Security:sendResetMail}

send_inscription_mail:
    path: /inscriptionMail/{id}
    defaults: {_controller: OSELUserBundle:Security:sendInscriptionMail, id: 0}

construction:
    path: /construction
    defaults: {_controller: OSELCoreBundle:Core:construction}

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"