# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
# authentication failure event listener
    acme.security.authentication_failure_event_listener:
        class: OSEL\UserBundle\Listener\AuthenticationListener
        arguments: ['@security.authorization_checker', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }

# authentication success event listener
    acme.security.interactive_login_listener:
        class: OSEL\UserBundle\Listener\AuthenticationListener
        arguments: ['@security.authorization_checker', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }


    maintenance_listener:
            class: OSEL\CoreBundle\Listeners\MaintenanceListener
            arguments:
                - "%isLocked%"
                - "@twig"
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
