<?php

namespace OSEL\MusicsheetBundle\Repository;

/**
 * MusicsheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicsheetRepository extends \Doctrine\ORM\EntityRepository
{
}
