<?php

namespace OSEL\MusicsheetBundle\Repository;

/**
 * PartsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartsRepository extends \Doctrine\ORM\EntityRepository
{
}
