<?php

namespace OSEL\MusicsheetBundle\Repository;

/**
 * SheetTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SheetTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
