<?php

namespace OSEL\EventBundle\Repository;

/**
 * RidingGroupMembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RidingGroupMembreRepository extends \Doctrine\ORM\EntityRepository
{
}
