<?php

namespace OSEL\EventBundle\Repository;

/**
 * SubEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
