<?php

namespace OSEL\EventBundle\Repository;

/**
 * RidingGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RidingGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
