<?php

namespace OSEL\ScoreBundle\Repository;

/**
 * BioComposerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BioComposerRepository extends \Doctrine\ORM\EntityRepository
{
}
