<?php

namespace OSEL\ScoreBundle\Repository;

/**
 * ComposerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComposerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActiveComposers($letter)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.scores', 'c')
            ->addSelect('c')
            ->where('c.actif = :actif')
            ->setParameter('actif', true)
            ->andWhere('a.composer LIKE :composer')
            ->setParameter('composer', $letter . "%")
            ->orderBy('a.composer')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findComposers($letter)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.scores', 'c')
            ->addSelect('c')
            ->andWhere('a.composer LIKE :composer')
            ->setParameter('composer', $letter . "%")
            ->orderBy('a.composer')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function myFindAll()
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->orderBy('a.composer')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
