<?php

namespace OSEL\ScoreBundle\Repository;

/**
 * ImgComposerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgComposerRepository extends \Doctrine\ORM\EntityRepository
{
}
