<?php

namespace OSEL\ScoreBundle\Repository;

/**
 * PartsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInstrumentParts(array $instruments)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.instrument', 'c')
            ->addSelect('c')
            ->leftJoin('a.musicsheet', 'd')
            ->addSelect('d')
            ->where('d.actif = :actif')
            ->setParameter('actif', true)
        ;

        $qb->andWhere($qb->expr()->in('c.id', $instruments));

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function getPartsByMusicsheet($id)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.musicsheet', 'c')
            ->addSelect('c')
        ;

        $qb->where($qb->expr()->in('c.id', $id));

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
