osel_score_index:
    path:     /library/{idComposer}/{idScore}
    defaults: { _controller: ScoreBundle:Score:index, idComposer: 0, idScore: 0 }
    options:
            expose: true

osel_score_gestion:
    path:     /gestion/{letter}/{idComposer}/{idScore}
    defaults: { _controller: ScoreBundle:Score:gestion, letter: a, idComposer: 0, idScore: 0 }
    options:
            expose: true

osel_score_upload_ajax:
    path:     /uploadAjax/{id}
    defaults: { _controller: ScoreBundle:Score:uploadAjax, id: 0}
    options:
            expose: true

osel_score_delete_part:
    path:     /supprimer-partition/{id}
    defaults: { _controller: ScoreBundle:Score:deletePart, id: 0}
    options:
            expose: true

osel_score_delete_score:
    path:     /supprimer-toute-la-partition/{id}
    defaults: { _controller: ScoreBundle:Score:deleteScore, id: 0}
    options:
            expose: true

osel_score_create_score:
    path:     /creer-partition/{id}
    defaults: { _controller: ScoreBundle:Score:createScore, id: 0}

osel_score_add_composer:
    path:     /ajouter-un-compositeur/{id}
    defaults: { _controller: ScoreBundle:Score:addComposer, id: 0}
    options:
            expose: true

osel_score_upload_parts:
    path:     /upload-partitions/{id}
    defaults: { _controller: ScoreBundle:Score:uploadParts, id: 0}

osel_score_modify_ajax_score:
    path:     /creer-partition/{id}
    defaults: { _controller: ScoreBundle:Score:modifyAjaxScore, id: 0}
    options:
            expose: true

osel_score_download_part:
    path:     /télécharger-partition/{id}
    defaults: { _controller: ScoreBundle:Score:downloadPart, id: 0}

osel_score_view_part:
    path:     /apercu-partition/{id}
    defaults: { _controller: ScoreBundle:Score:viewPart, id: 0}

osel_score_modify_part:
    path:     /modifier-partition/{id}
    defaults: { _controller: ScoreBundle:Score:modifyPart, id: 0}
    options:
            expose: true

osel_score_activate_part:
    path:   /Activation-partition/{id}
    defaults:  { _controller: ScoreBundle:Score:activatePart, id: 0}

osel_score_activate_score:
    path:   /Activation-morceau/{id}
    defaults:  { _controller: ScoreBundle:Score:activateScore, id: 0}

osel_score_search:
    path:   /search/{text}
    defaults:  { _controller: ScoreBundle:Score:search}
    options:
            expose: true

osel_score_view_composer:
    path:     /apercu-compositeur/{id}
    defaults: { _controller: ScoreBundle:Score:viewComposer, id: 0}

osel_score_add_composer_bio:
    path:     /ajouter-un-texte-compositeur/{idcomposer}/{id}
    defaults: { _controller: ScoreBundle:Score:addComposerBio, idcomposer: 0, id: 0}

osel_score_add_composer_image:
    path:     /ajouter-une-photo-compositeur/{idcomposer}
    defaults: { _controller: ScoreBundle:Score:addComposerImg, idcomposer: 0}

osel_score_reset_scores:
    path:     /reset-scores
    defaults: { _controller: ScoreBundle:Score:resetScores}
