osel_score_index:
    path:     /
    defaults: { _controller: ScoreBundle:Score:index}

osel_score_gestion:
    path:     /gestion/{idComposer}/{idScore}/{idPart}
    defaults: { _controller: ScoreBundle:Score:gestion, idComposer: 0, idScore: 0, idPart: 0 }