<?php

namespace OSEL\DocBundle\Repository;

/**
 * CategoryDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
