<?php

namespace OSEL\DocumentBundle\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDir($id, $criteria, $order)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.directory', 'c')
            ->addSelect('c')
        ;

        $qb->where($qb->expr()->in('c.id', $id));
        $qb->orderBy('a.' . $criteria, $order);

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
