<?php

namespace OSEL\MediaBundle\Repository;

/**
 * YearMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
