<?php

namespace OSEL\InfoBundle\Repository;

/**
 * RedirectionMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectionMailRepository extends \Doctrine\ORM\EntityRepository
{
}
