#src/Osel/CoreBundle/Resources/config/routing.yml

osel_core_home:
    path:     /
    defaults: { _controller: OSELInfoBundle:Info:agenda }

osel_core_agenda:
    path:     /infos/agenda
    defaults: { _controller: OSELInfoBundle:Info:agenda }

osel_user_index:
    path:     /Users/{page}/{criteria}/{desc}/{active}/{nbPerPage}
    defaults: { _controller: OSELUserBundle:User:index, page: 1, criteria: lastname, desc: 0, active: 0, nbPerPage: 20}

osel_user_view:
    path:     /User/{id}
    defaults: { _controller: OSELUserBundle:User:view, id: 0 }

osel_user_csv_options:
    path:     /UserExport-options
    defaults: { _controller: OSELUserBundle:ExportFiles:index}

osel_user_export:
    path:     /UserExport/{id}/{email}/{instrument}/{adress}/{phone}/{birthday}/{emergency}
    defaults: { _controller: OSELUserBundle:ExportFiles:export}

osel_user_export_contact:
    path:     /UserExportContact
    defaults: { _controller: OSELUserBundle:ExportFiles:exportContact}

osel_musicsheet_index:
    path:     /Musicsheets
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:index}

osel_musicsheet_gestion:
    path:     /Musicsheets/Gestion/{idComposer}/{idMusicsheet}/{idPart}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:gestion, idComposer: 0, idMusicsheet: 0, idPart: 0 }

osel_musicsheet_view:
    path:     /Musicsheet/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:view, id: 0 }

osel_musicsheet_view_part:
    path:     /Musicsheet/part/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:viewPart, id: 0 }

osel_musicsheet_modify:
    path:     /Musicsheet/modify/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:modify, id: 0 }
    options:
        expose: true

osel_musicsheet_modify_complete:
    path:     /Musicsheet/modifycomplete/{id}
    defaults: { _controller: OSELMusicsheetBundle:Musicsheet:modifyComplete, id: 0 }
    options:
        expose: true

osel_info_index:
    path:     /infos_pratique
    defaults: { _controller: OSELInfoBundle:Info:index }

osel_info_redirections:
    path:     /infos/redirections
    defaults: { _controller: OSELInfoBundle:Info:redirections }

osel_info_redirections_gestion:
    path:     /infos/redirections/gestion
    defaults: { _controller: OSELInfoBundle:Info:gestion }

osel_info_redirections_modify:
    path:     /infos/redirections/modify/{id}
    defaults: { _controller: OSELInfoBundle:Info:modify }

osel_info_redirections_delete:
    path:     /infos/redirections/delete/{id}
    defaults: { _controller: OSELInfoBundle:Info:delete }



