<?php

namespace OSEL\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupesRepository extends EntityRepository
{
}
