<?php

namespace OSEL\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatutsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutsRepository extends EntityRepository
{
}
