<?php

namespace OSEL\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getUsers($page, $nbPerPage, $enabled, $criteria, $desc)
    {
		$qb = $this->createQueryBuilder('a')
                    ->leftJoin('a.instruments', 'c')
                    ->addSelect('c');

		if($enabled){
			$qb->where('a.enabled = :enabled')
				->setParameter('enabled', true);
		}
		if($desc){
			$order = 'DESC';
		}
		else{
			$order = 'ASC';
		}
			
		if($criteria == 'instruments')
		{
			$qb->orderBy('c.instrument', $order);
		}
		else{
			$qb->orderBy('a.'.$criteria, $order);
		}
	
		

        $qb->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
        ;

        return new Paginator($qb, true);

	}

	public function getExportQuery()
    {
        $queryBuilder = $this->createQueryBuilder('a');
	    $query = $queryBuilder->getQuery();
	    //$results = $query->getResult();
	    return $query;
    }
}
